### ISSUE TITLE
Broken double slot conversion in timer intents

### ISSUE THREAD

**Issue by mots** [JarvyJ/HomeIntent#137]
So I tried out the timer component, but couldn't initially get it to work - it never correctly parsed the time I gave it.
Looking at the sentences, they all look something like this:

`set timer (<time>){hours:!int} [($partial_time)] hours`

However, the rhasspy doc [states](https://rhasspy.readthedocs.io/en/latest/training/#number-ranges):
> ...will automatically be converted to an integer for you. 

So I think what was happening was a double conversion, once the built-in one from the number range and then the explicit one. I tried removing the `!int` from the sentences and timers started working! 🎉 . I think we should remove this from the intents.

**Comment by mots** [comment]
I am in fact running 2.5.11!

> I think you might've fixed the #25!
🎉

**Comment by JarvyJ** [comment]
But yeah, we should totally get this removed from intents, we could also sneak in #116 while in the timer code. And then update to 2.5.11 overall (which is now just increasing the number in the generate_dockerfiles.py, run some tests, and then let github do its thing!).

I should be able to get to it within the next couple of days, if you have time feel free to PR
