### ISSUE TITLE
Saving settings not responsive if incorrect URL formatting

### ISSUE THREAD

**Issue by oerkel47** [JarvyJ/HomeIntent#231]
Hi again,
I will keep documenting the issues I find.

If you enter an unexpected HA URL (eg: IP:PORT instead of http://IP:PORT) hitting the save button will not do anything. There should at least be an error thrown into the log or some kind of feedback inside the UI.

**Comment by JarvyJ** [comment]
We now have pydantic errors being returned in the frontend. There is more work ongoing in #240 and #238 to make the UI better from a UX point of view!

Going to close this for now as the base issue here has been resolved and additional tickets have been created! At least this change will be in the next release!

Thanks again for reporting!
