### ISSUE TITLE
Timer not working with satellites

### ISSUE THREAD

**Issue by thundergreen** [JarvyJ/HomeIntent#258]
I setup timer and it confirms me the time set. But after running down the time I don't hear any sound.

Setup:

Rhasspy on seperate Server --> ESP32 Satellite communicating via MQTT with Rhasspy
HomeIntent on seperate server --> Communicating via MQTT to Rhasspy

**Comment by JarvyJ** [comment]
Yeah, this is one of the outcomes of not properly supporting satellites... I've changed the title and marked it as a bug and will get to it in a bit. There's an issue with the timer completion message not knowing what satellite to respond to and I want to figure out a nice way of keeping track or forwarding the satellite information on.

**Comment by thundergreen** [comment]
sounds great! thanks a lot for the efforts in this project. SInce Snips died back in the days (Which was really a powerful tool) I started playing around with Rhasspy but never really got all setup. With this app it is more than easy to setup voice assistant in less than 5 minutes :)

**Comment by JarvyJ** [comment]
The fix has been in for a while and I finally got around to updating the docs. Closing this out for now!
