### ISSUE TITLE
[Translation development] If language files are missing, home intent won't start up correctly

### ISSUE THREAD

**Issue by oerkel47** [JarvyJ/HomeIntent#261]
If there is a language file missing for any component (that is not on ignore list) home intent won't start up correctly.
For example if 'home_assistant/cover/de.py' has not been created yet, the english fallback will apparently not load because of the name/language mismatch. 

> 2022-01-02 17:36:07,625 INFO root Using language: de
{'logbook', 'cover', 'system_log', 'input_button', 'tts', 'input_datetime', 'binary_sensor', 'input_text', 'frontend', 'notify', 'persistent_notification', 'recorder', 'zone', 'camera', 'homeassistant', 'sensor', 'automation', 'counter', 'mqtt', 'fan', 'input_boolean', 'sun', 'timer', 'group', 'script', 'person', 'input_number', 'scene', 'light', 'input_select', 'cloud', 'device_tracker', 'switch'}
2022-01-02 17:36:07,665 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.cover.base_cover...
2022-01-02 17:36:07,667 ERROR root The slot 'cover_open_entity' should start with the module name (en) in the class home_intent.components.home_assistant.cover.en
Traceback (most recent call last):
  File "home_intent/__main__.py", line 63, in main
    _load_integrations(settings, home_intent)
  File "home_intent/__main__.py", line 83, in _load_integrations
    loaded_builtin_components = _load_builtin_components(components, home_intent)
  File "home_intent/__main__.py", line 112, in _load_builtin_components
    integration.setup(home_intent)
  File "/usr/src/app/home_intent/components/home_assistant/__init__.py", line 78, in setup
    home_intent.register(cover.Cover(home_assistant_component), cover.intents)
  File "/usr/src/app/home_intent/home_intent.py", line 108, in register
    f"The slot '{slot}' should start with the module name ({module_name}) "
home_intent.home_intent.HomeIntentException: The slot 'cover_open_entity' should start with the module name (en) in the class home_intent.components.home_assistant.cover.en

I assume this is not 100% working as intended.

**Comment by JarvyJ** [comment]
Oh that's not good. It looks like it has to do with how the fallback file gets loaded. Thanks for reporting, I'll take a look

**Comment by JarvyJ** [comment]
This should now also be fixed in [#263](https://github.com/JarvyJ/HomeIntent/pull/263/files#diff-f993119cb4f5216f9557ecf3dd3f0e3ec0b003575d33cc31ef0bef13cd11b8c6). The new module loading got a little weird on me, and I forgot about the fallback. I should get some automated testing in place (#228)... 

Also in [#263](https://github.com/JarvyJ/HomeIntent/pull/263/files#diff-5a60463aaa3d1ed686893152f53b22c0dc679d1d3cdf791f8561de0789928300R35-R40) is the ability to auto-set the Rhasspy url in the config if it's not provided to `rhasspy` as opposed to `localhost` so everything can work in the multi-docker setup!

**Comment by JarvyJ** [comment]
Got #263 merged, let me know if it works for you!

**Comment by oerkel47** [comment]
Thanks! It's working for me.
