### ISSUE TITLE
Language setting in docker-compose.yaml does not affect Rhasspy TTS language

### ISSUE THREAD

**Issue by oerkel47** [JarvyJ/HomeIntent#262]
Hi @JarvyJ .

Setting LANGUAGE=de and --profile de in the compose file does not change TTS language to the German one. It will stay English.

**Comment by JarvyJ** [comment]
I got this fixed in [#263](https://github.com/JarvyJ/HomeIntent/pull/263/files#diff-9fdb6681865fc15235ac9af265fa3ab614ee0ce8526f20f0c3cc2150ea474303). The `audio_config` will now setup nanotts or espeak depending on the supported languages!

Thanks for reporting!

**Comment by JarvyJ** [comment]
Got it merged in, let me know if it works for you!

**Comment by oerkel47** [comment]
Appears to be working as well, thanks!
