### ISSUE TITLE
Managed Satellites Customisation

### ISSUE THREAD

**Issue by fifise77** [JarvyJ/HomeIntent#525]
Hello, 

First thank for your hard work and this amazing app.
I am trying to use it with french seapking language

is there a way to managed the Satellite to use "arecord" as a audio recording instead of "PyAudio" ?

_Originally posted by @fifise77 in https://github.com/JarvyJ/HomeIntent/discussions/523_

**Comment by JarvyJ** [comment]
Answered in discussions. Closing the issue for now.
