### ISSUE TITLE
How to access entities of a specific room?

### ISSUE THREAD

**Issue by alve89** [JarvyJ/HomeIntent#546]
First of all @JarvyJ: Awesome, awesome work, really!

Second: I didn't find any automatically configured sentences in Rhasspy `intents/home_intent.ini` which bring the ability to access a specific room (living room, bedroom, ...). I just wanted to turn off all the lights in the living room, but only one (randomly one or the other) is turned of. How can I add rooms?

And how can I contribute to this awesome project, e. g. adding more sentences to the defaults, translating, ...?

Regarding the last: I'm in a German profile, most of the sentences is translated to German but not all intents, e. g. 
```
[home_intent.components.home_assistant.group.base_group.turn_on_group]
turn on [the] ($group)
```

Where is the right path to translate this to German?

**Comment by JarvyJ** [comment]
Hey! Glad you're liking Home Intent. Yeah, unfortunately, the German translation doesn't support groups at the moment. If you wanted to add it, it would be as simple as adding a `de.py` file to the [group folder](https://github.com/JarvyJ/HomeIntent/tree/main/home_intent/components/home_assistant/group). You can see an example in the [light folder](https://github.com/JarvyJ/HomeIntent/tree/main/home_intent/components/home_assistant/light) as to what that looks like.

If you want more information on how to translate components, there is some info in [the docs](https://homeintent.io/reference/translations/developing-translations/). Let me know if you have any questions!

As far as your specific problem. The best thing would be to add in group support to German and then set up all of your living room lights in a group. From there, you could add the individual lights in the "Ignore Entities" setting and have Home Intent only control the group.

**Comment by alve89** [comment]
I'll try to add a translation! 

But my question wasn't about groups but about rooms. So changing the HA config to manage all devices in groups **instead** of rooms (I manage my devices by both rooms **and** groups) seems not to be the proper way.

For example I have assigned all devices (not only lights) to their associated rooms. Additionally have groups with all lights (which sometimes are of the entity type `switch`).

So in the end: Is there any plan to support HA rooms properly?

**Comment by JarvyJ** [comment]
At a cursory glance, it doesn't seem as if Home Assistant has [API control](https://developers.home-assistant.io/docs/core/entity) over rooms, so I'm probably not going to go through implementing it.
