### ISSUE TITLE
Timeout while restarting / configuring satellites

### ISSUE THREAD

**Issue by alve89** [JarvyJ/HomeIntent#547]
By now I have two satellites (because there's no economic way to buy more RPi Zero's)...

This error occurs way too often (and when it occurs it's repeating over and over - I was not able to finish a single HI restart in the last 30 minutes and I'm still trying). The configuration is not the problem, it already worked properly.

```
26.11.2022, 20:06:05 INFO home_intent.rhasspy_api Trying to connect to Rhasspy at http://localhost:12101
26.11.2022, 20:06:06 INFO root Using language: de
26.11.2022, 20:06:06 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.cover.base_cover...
26.11.2022, 20:06:06 INFO home_intent.home_intent Sentences look good!
26.11.2022, 20:06:06 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.fan.base_fan...
26.11.2022, 20:06:06 INFO home_intent.home_intent Sentences look good!
26.11.2022, 20:06:06 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.group.base_group...
26.11.2022, 20:06:06 INFO home_intent.home_intent Sentences look good!
26.11.2022, 20:06:06 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.light.base_light...
26.11.2022, 20:06:06 INFO home_intent.home_intent Sentences look good!
26.11.2022, 20:06:06 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.shopping_list.base_shopping_list...
26.11.2022, 20:06:06 INFO home_intent.home_intent Sentences look good!
26.11.2022, 20:06:06 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.switch.base_switch...
26.11.2022, 20:06:06 INFO home_intent.home_intent Sentences look good!
26.11.2022, 20:06:06 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.weather.base_weather...
26.11.2022, 20:06:06 INFO home_intent.home_intent Sentences look good!
26.11.2022, 20:06:06 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.media_player.base_media_player...
26.11.2022, 20:06:06 INFO home_intent.home_intent Sentences look good!
26.11.2022, 20:06:06 INFO home_intent.updater No updates to perform this release!
26.11.2022, 20:06:06 INFO home_intent.home_intent 


====================================================================================================
Setting up the base Rhasspy instance
====================================================================================================


26.11.2022, 20:06:06 INFO home_intent.home_intent Checking profile
26.11.2022, 20:06:06 INFO home_intent.home_intent Installing profile
26.11.2022, 20:06:07 INFO home_intent.home_intent Restarting Rhasspy...
26.11.2022, 20:06:09 INFO home_intent.home_intent Profile is up to date, nothing to download
26.11.2022, 20:06:09 INFO home_intent.home_intent Setting up managed satellites
26.11.2022, 20:06:09 INFO home_intent.home_intent 


====================================================================================================
Setting up satellite config for rpisat01
====================================================================================================


26.11.2022, 20:06:09 INFO home_intent.rhasspy_api Trying to connect to Rhasspy at http://rpisat01:12101
26.11.2022, 20:06:39 ERROR root TimeoutError: 
Traceback (most recent call last):
  File "/usr/src/app/home_intent/__main__.py", line 64, in main
    home_intent.initialize()
  File "/usr/src/app/home_intent/home_intent.py", line 190, in initialize
    self._setup_satellites()
  File "/usr/src/app/home_intent/home_intent.py", line 240, in _setup_satellites
    satellite_api, satellite_config, satellite_id, satellite_info
  File "/usr/src/app/home_intent/audio_config.py", line 68, in add_audio_settings_to_satellite
    microphone_devices = satellite_api.get("/api/microphones")
  File "/usr/src/app/home_intent/rhasspy_api.py", line 40, in get
    raise RhasspyError(response.text)
home_intent.rhasspy_api.RhasspyError: TimeoutError: 
```

Is it really necessary to configure them with every restart? I'm not in the code but even after this error the sentences and therefore the intents are recognised but not handled anymore. Maybe without configuring the satellites with every restart and instead finishing Rhasspy's training there would not occur a real problem in the voice recognition system?

**Comment by alve89** [comment]
One workaround is
1. disconnecting all the satellites from the network,
2. restarting HI and let it train Rhasspy and then
3. reconnecting the satellites to the network.

This finishes the Rhasspy training properly and the satellites will work as expected (when they are already configured properly).

**Comment by JarvyJ** [comment]
Oooh yeah, that's not good. If it times out trying to connect, it should probably just continue on. I'll look into fixing it.

**Comment by alve89** [comment]
As far as I understand this error message it times out while adding the audio settings (mic, speaker), is this correct? Assuming this would be correct, I tried to removing the `sounds_device` and the `microphone_device` to prevent trying adding audio settings to the satellites but the error still occurs

```
  managed_satellites:
    rpisat01:
      url: http://rpisat01:12101
    rpisat02:
      url: http://rpisat02:12101
```

So actually IMHO a satellite would only needed to be reconfigured if any settings of the MQTT broker changed, everything else is from the `default_configs` anyways.

**Comment by JarvyJ** [comment]
Yeah, that would be great. However, the struggle is if someone logs into their satellite and changes a setting then breaks their setup and want to just restart HI to fix it. I wouldn't be able to detect that based on a config change.

So it ends up being a bit of a balance.

**Comment by alve89** [comment]
That's a comprehensible argument! The question is: What is causing the timeout? Is it the network connection to the satellite or is it the satellite itself? It seems to me the connections worked but the configuration times out - do you know that?

May be a checkbox for each satellite would be a solution: "Re-configure satellite X"? Or a button for only training Rhasspy without configurering all satellites?

**Comment by JarvyJ** [comment]
I tried replicating this a few times and couldn't get a Timeout error, even when Home Intent couldn't connect to the satellite. After a couple of seconds it just moved on. Can you show more of the logs?
